set nocompatible

" GENERAL OPTIONS {{{

" Short Messages - Don't give me that file already being edited nonsense
set shortmess+=A
" Switch between buffers without saving the buffer first
set hidden
"Itch that bufferscratching itch with jumping around.
set switchbuf=useopen
" Search settings
set showmatch
set incsearch
set grepprg=ack-grep\ --column\ $*
" Tabbing settings
set autoindent
set expandtab
set shiftwidth=2
set smarttab
set softtabstop=4
set tabstop=2
" wild menu
set wildmenu
set completeopt=longest,menuone,preview

" default to using marker folds
set foldmethod=marker

" show me the command!
set showcmd

" Turn off mouse abilities
set mouse=

" Cscope options
if has('cscope')
  set cscopetag cscopeverbose

  if has('quickfix')
    set cscopequickfix=s-,c-,d-,i-,t-,e-
  endif

  cnoreabbrev csa cs add
  cnoreabbrev csf cs find
  cnoreabbrev csk cs kill
  cnoreabbrev csr cs reset
  cnoreabbrev csh cs help
  cnoreabbrev csss cs show

  command! -nargs=0 Cscope cs add $VIMSRC/src/cscope.out $VIMSRC/src
endif

" Omnicompletion ahoy
filetype plugin on
set ofu=syntaxcomplete#Complete

set thesaurus+=~/.vim/mthesaur.txt

" Display whitespace
" Display statusline always
" taken from http://techspeak.plainlystated.com/2009/05/vim-statusline.html

set laststatus=2
set statusline=
set statusline+=%<\                       " cut at start
set statusline+=%f\                       " relative path
set statusline+=%m                        " modifiable flag
set statusline+=%=                        " seperate between right- and left-aligned
set statusline+=%2*[%n]%*\                " buffer number, and flags
set statusline+=%1*%y%*%*\                " file type
set statusline+=%10((%v,%l)%)\            " line and column
set statusline+=%P                        " percentage of file



" }}}
" MAPPINGS {{{
let mapleader = "\\"
let maplocalleader = "["

" lhs comments (line commenting)
map ,# :s/^/#/<CR>:nohlsearch<CR>
map ,/ :s/^/\/\//<CR>:nohlsearch<CR>
map ,> :s/^/> /<CR>:nohlsearch<CR>
map ," :s/^/\"/<CR>:nohlsearch<CR>
map ,% :s/^/%/<CR>:nohlsearch<CR>
map ,! :s/^/!/<CR>:nohlsearch<CR>
map ,; :s/^/;/<CR>:nohlsearch<CR>
map ,- :s/^/--/<CR>:nohlsearch<CR>
map ,c :s/^\/\/\\|^--\\|^> \\|^[#"%!;]//<CR>:nohlsearch<CR>
" wrapping comments (line commenting)
map ,* :s/^\(.*\)$/\/\* \1 \*\//<CR>:nohlsearch<CR>
map ,( :s/^\(.*\)$/\(\* \1 \*\)/<CR>:nohlsearch<CR>
map ,< :s/^\(.*\)$/<!-- \1 -->/<CR>:nohlsearch<CR>
map ,d :s/^\([/(]\*\\|<!--\) \(.*\) \(\*[/)]\\|-->\)$/\2/<CR>:nohlsearch<CR>
" [okay] commenting
map ,[ 0/$:nohlsearch<CR>a [okay]

" a grep mapping - doesn't add * to the end because it will search all files
" in cur directory, and ack-grep is smart enough to know that.
map <Leader>g :grep <cword>
map <Leader>cc :source ~/.vimrc<CR>

" go to new file
map gn :e <cfile><CR>

" open file through xdg-open
nmap gr :exec ":silent !xdg-open ".expand("<cWORD>")

" Set gp to select the last pasted text
nnoremap <expr> gp '`[' . strpart(getregtype(), 0, 1) . '`]'

" trim ending whitespace
map <Leader>tr :%s/\s\+$//g

" quick fix and tag select shortcuts 
nmap [g :cp
nmap ]g :cn
nmap [t :tp
nmap ]t :tn

" swap two words next to each other, like xp but word wise
:nnoremap <silent> xw "_yiw:s/\(\%#\w\+\)\(\_W\+\)\(\w\+\)/\3\2\1/<CR><c-o><c-l>

" toggle paste mode
map <F2> :set paste!<CR>
" no highlighting after search with F3
map <F3> :nohlsearch<CR>
" build on f4
map <F4> :make<CR>

map <F5> :SyntasticCheck<CR>

let g:syntastic_shell = "/bin/bash"

" highlight class of character under the word
nmap <silent> <F10>   :echo "hi<" . synIDattr(synID(line("."),col("."),1),"name") . '> trans<' . synIDattr(synID(line("."),col("."),0),"name") . "> lo<" . synIDattr(synIDtrans(synID(line("."),col("."),1)),"name") . ">"<CR>
" paste input toggle
set pastetoggle=<F2>
" }}}
"
" vim: foldmethod=marker
