set nocompatible

" GENERAL OPTIONS {{{

" Short Messages - Don't give me that file already being edited nonsense
set shortmess+=A
" Switch between buffers without saving the buffer first
set hidden
"Itch that bufferscratching itch with jumping around.
set switchbuf=useopen
" Search settings
set showmatch
set incsearch
set grepprg=ack-grep\ --column\ $*
" Tabbing settings
set autoindent
set expandtab
set shiftwidth=2
set smarttab
set softtabstop=4
set tabstop=2
" wild menu and menu completion
set wildmenu
set completeopt=longest,menuone
" default to using marker folds
set foldmethod=marker
" show me the command!
set showcmd
" Turn off mouse abilities
set mouse=
" if we have a thesaurus (use with ctrl-x ctrl-t)
set thesaurus+=~/.vim/mthesaur.txt
" for faster movement, we have line numbers enabled
set cursorline
set relativenumber
set number

set path+=**
set wildignore+=**/node_modules/**
set wildignore+=**/python2.7/**
set wildignore+=**/site-packages/**
set wildignore+=**/build/**

set swapfile
set undofile
set undodir=~/.vim/.undo//
set backupdir=~/.vim/.backup//
set directory=~/.vim/.swp//
silent !test -d ~/.vimrc/.swp || mkdir -p ~/.vim/.{undo,backup,swp}



" Omnicompletion ahoy
filetype plugin on
set ofu=syntaxcomplete#Complete
let g:syntastic_shell = "/bin/bash"


" Display statusline always
" taken from http://techspeak.plainlystated.com/2009/05/vim-statusline.html
set laststatus=2
set statusline=
set statusline+=%<\                       " cut at start
set statusline+=%f\                       " relative path
set statusline+=%m                        " modifiable flag
set statusline+=%=                        " seperate between right- and left-aligned
set statusline+=%2*[%n]%*\                " buffer number, and flags
set statusline+=%1*%y%*%*\                " file type
set statusline+=%10((%v,%l)%)\            " line and column
set statusline+=%P                        " percentage of file
" }}}
" MAPPINGS {{{
let mapleader = "\\"
let maplocalleader = "["
map <Leader>cc :source ~/.vimrc<CR>

" commenting tips from http://vim.wikia.com/wiki/Easy_(un)commenting_out_of_source_code
" lhs comments (line commenting)
map ,# :s/^/#/<CR>:nohlsearch<CR>
map ,/ :s/^/\/\//<CR>:nohlsearch<CR>
map ,> :s/^/> /<CR>:nohlsearch<CR>
map ," :s/^/\"/<CR>:nohlsearch<CR>
map ,% :s/^/%/<CR>:nohlsearch<CR>
map ,! :s/^/!/<CR>:nohlsearch<CR>
map ,; :s/^/;/<CR>:nohlsearch<CR>
map ,- :s/^/--/<CR>:nohlsearch<CR>
map ,c :s/^\/\/\\|^--\\|^> \\|^[#"%!;]//<CR>:nohlsearch<CR>
" wrapping comments (line commenting)
map ,* :s/^\(.*\)$/\/\* \1 \*\//<CR>:nohlsearch<CR>
map ,( :s/^\(.*\)$/\(\* \1 \*\)/<CR>:nohlsearch<CR>
map ,< :s/^\(.*\)$/<!-- \1 -->/<CR>:nohlsearch<CR>
map ,d :s/^\([/(]\*\\|<!--\) \(.*\) \(\*[/)]\\|-->\)$/\2/<CR>:nohlsearch<CR>
" [okay] commenting
map ,[ 0/$:nohlsearch<CR>a [okay]


" EXTRA G COMMANDS
" a grep mapping - doesn't add * to the end because it will search all files
" in cur directory, and ack-grep is smart enough to know that.
map <Leader>g :grep <cword>
" open file through xdg-open, use on images and the like
nmap gr :exec ":silent !xdg-open ".expand("<cWORD>")
" Set gp to select the last pasted text
nnoremap <expr> gp '`[' . strpart(getregtype(), 0, 1) . '`]'
" trim ending whitespace (silently)
map <silent> <Leader>tr :silent! %s/\s\+$//g

vmap <leader>y :w! /tmp/vitmp<CR>
nmap <leader>p :r! cat /tmp/vitmp<CR>

" quick fix and tag select shortcuts
nmap [b :bp
nmap ]b :bn
nmap [g :cp
nmap ]g :cn
nmap [t :tp
nmap ]t :tn

" swap two words next to each other, like xp but word wise
" from http://vim.wikia.com/wiki/Swapping_characters,_words_and_lines
nnoremap <silent> xw "_yiw:s/\(\%#\w\+\)\(\_W\+\)\(\w\+\)/\3\2\1/<CR><c-o><c-l>

" FUNCTION KEYS
" paste input toggle
set pastetoggle=<F2>
" no highlighting after search with F3
map <F3> :nohlsearch<CR>
" build on f4
map <F4> :w<CR>:silent :make<CR>:cw<CR>
map <F5> :SyntasticCheck<CR>
" highlight class of character under the word
nmap <silent> <F10>   :echo "hi<" . synIDattr(synID(line("."),col("."),1),"name") . '> trans<' . synIDattr(synID(line("."),col("."),0),"name") . "> lo<" . synIDattr(synIDtrans(synID(line("."),col("."),1)),"name") . ">"<CR>
" }}}
"
" vim: foldmethod=marker
